baseURL: http://example.org/
title: Lazysizes with Hugo
# alternate copyright company text
copyright: Future Web Design
# controls number of pages displayed on list pages
paginate: 5
# controls the summary length (words) on list pages
summaryLength: 7
# this is required so that Hugo will render HTML in markdown
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  image:
    widths: [600, 900, 1300]
    densities: [1,2]
    class: img-fluid
    figureClass: figure
    disableLazysizes: false
    lqip:
      size: 50
      blur: 3
      disable: false